@ECHO OFF

SET APPLICATION_NAME=MockTCPServer
SET SCRIPT_FOLDER=%~dp0
SET MAINCLASS=io.cloudracer.mocktcpserver.MockTCPServer
SET CLASSPATH=*
REM SET SERVER_PARAMS=-Dmocktcpserver.configuration.initialisation.enabled=true

ECHO APPLICATION_NAME:%APPLICATION_NAME%.
ECHO SCRIPT_FOLDER:%SCRIPT_FOLDER%.
ECHO MAINCLASS:%MAINCLASS%.
ECHO CLASSPATH:%CLASSPATH%.
REM ECHO SERVER_PARAMS:%SERVER_PARAMS%.

START "%APPLICATION_NAME%" /D "%SCRIPT_FOLDER%" java %SERVER_PARAMS% %MAINCLASS% %1